version: "3.9"

services:
  node:
    restart: unless-stopped
    container_name: api
    build:
      dockerfile: Dockerfile.test.node
    depends_on:
      - db
      - cache
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_USER: $TEST_POSTGRES_USER
      POSTGRES_PASSWORD: $TEST_POSTGRES_PASSWORD
      POSTGRES_DB: $TEST_POSTGRES_DB
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    expose:
      - "5432"
  cache:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    container_name: cache
    command: redis-server --appendonly yes
    volumes:
      - type: volume
        source: redis_data
        target: /data
    expose:
      - "6379"
  webserver:
    image: nginx:1.22.0-alpine
    restart: unless-stopped
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl-prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/certs
    depends_on:
      - node

volumes:
  postgres_data:
  redis_data:
