FROM node:16-bullseye-slim AS builder

RUN adduser node node

RUN mkdir /home/node/src

WORKDIR /home/node/src

COPY ./keys ./keys/

COPY --chown=node:node package-lock.json package.json ./

COPY --chown=node:node .env.test babel.config.js postcss.config.js tsconfig.json ./

COPY --chown=node:node ./server/auth/ ./server/auth/

COPY --chown=node:node ./certs/daazzll.dev* ./

COPY --chown=node:node ./prisma ./prisma/

RUN npm ci && npm run babel:auth:server

RUN npm prune --production

##### - Stage 2 - run server #######

FROM node:16-bullseye-slim

RUN adduser node node

RUN mkdir /home/node/src

WORKDIR /home/node/src

COPY ./keys ./keys/

COPY --chown=node:node package-lock.json package.json ./

COPY --chown=node:node .env.test babel.config.js postcss.config.js tsconfig.json ./

COPY --chown=node:node ./certs/daazzll.dev* ./

COPY --chown=node:node ./prisma ./prisma

COPY --from=builder /home/node/src/lib ./lib

COPY --from=builder /home/node/src/node_modules ./node_modules

EXPOSE 8433

CMD ["npm", "run", "docker:start:auth"]