version: "3.9"

services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DEV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DEV_POSTGRES_DB}
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
  cache:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    container_name: cache
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis_data
        target: /data
      - type: bind
        source: ./.docker/redis.conf
        target: /usr/local/etc/redis/redis.conf
  webserver:
    image: nginx:1.22.0-alpine
    restart: unless-stopped
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl-dev/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/certs
volumes:
  postgres_data:
  redis_data:
