import crypto from "crypto";
import fs from "fs";
import util from "util";
import { RequestHandler, Request, Response, NextFunction } from "express";
import { v4 as uuidv4 } from "uuid";
import { redisClient } from "../../storageInit";
import { RedisAuthToken } from "../../custom-types";
import { regenToken, signedToken } from "../../utils/helpers/auth";
import prismaClient from "../../prismaClient";
import { handleJWT } from "../../utils/helpers";
import { PUB_KEY_PATH, PRIV_KEY_PATH } from "../../serverConfig";
